# Generated by Django 4.2.6 on 2023-11-03 19:09
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ekiladesign", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicite",
            name="is_updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
