# Generated by Django 4.2.6 on 2024-04-14 21:16
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ekiladesign", "0003_alter_publicite_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicite",
            options={
                "ordering": ["-is_created_at"],
                "verbose_name": "Publicite",
                "verbose_name_plural": "Publicities management",
            },
        ),
    ]
