# Generated by Django 4.2.6 on 2024-04-14 21:25
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ekiladesign", "0005_alter_publicite_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicite",
            options={
                "ordering": ["-is_created_at"],
                "verbose_name": "Publicity",
                "verbose_name_plural": "Advertising management",
            },
        ),
    ]
