# Generated by Django 4.2.6 on 2024-04-16 00:01
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ekiladesign", "0006_alter_publicite_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publicite",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="description"),
        ),
        migrations.AlterField(
            model_name="publicite",
            name="is_created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="is created at"
            ),
        ),
        migrations.AlterField(
            model_name="publicite",
            name="is_enable",
            field=models.BooleanField(default=True, verbose_name="is enable"),
        ),
        migrations.AlterField(
            model_name="publicite",
            name="is_updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="is updated at"),
        ),
        migrations.AlterField(
            model_name="publicite",
            name="pub_image",
            field=models.FileField(
                upload_to="uploads/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpeg", "jpg"]
                    )
                ],
                verbose_name="publicity image",
            ),
        ),
        migrations.AlterField(
            model_name="publicite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
