# Generated by Django 4.2.6 on 2023-12-09 19:55
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Radio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("url_flux_radio", models.URLField(blank=True, null=True)),
                ("url_server_radio", models.URLField()),
                ("url_api_radio", models.URLField(blank=True, null=True)),
                ("url_cover_default", models.URLField()),
                ("url_site", models.URLField()),
                (
                    "server_type",
                    models.CharField(
                        choices=[("shoutcast", "Shoutcast"), ("icecast", "Icecast")],
                        default="shoutcast",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_radio",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Radio",
                "verbose_name_plural": "Radios",
            },
        ),
    ]
