# Generated by Django 4.2.6 on 2024-02-04 05:48
import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("radio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="radio",
            name="radio_image_icon",
            field=models.FileField(
                blank=True,
                upload_to="uploads/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpeg", "jpg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="server_type",
            field=models.CharField(
                choices=[
                    ("shoutcast", "Shoutcast"),
                    ("icecast", "Icecast"),
                    ("everestcast", "EverestCast"),
                    ("centovacast", "CentovaCast"),
                    ("mediacp", "MediaCP"),
                    ("azuracast", "AzuraCast"),
                    ("everestpanel", "EverestPanel"),
                    ("radioking", "RadioKing"),
                ],
                default="shoutcast",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="url_api_radio",
            field=models.URLField(blank=True, default="", null=True),
        ),
    ]
