# Generated by Django 4.2.6 on 2024-03-10 22:26
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("radio", "0002_radio_radio_image_icon_alter_radio_server_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="radio",
            name="url_api_radio",
        ),
        migrations.AddField(
            model_name="radio",
            name="id_radioking",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="radio",
            name="radio_account_port",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="radio",
            name="sid",
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name="radio",
            name="station_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="radio",
            name="url_api_radio_current_song",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="radio",
            name="url_api_radio_history",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="radio",
            name="url_pannel_connexion",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="radio",
            name="username_radio_account",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="radio",
            name="server_type",
            field=models.CharField(
                choices=[
                    ("shoutcast", "Shoutcast"),
                    ("icecast", "Icecast"),
                    ("everestcast", "EverestCast"),
                    ("centovacast", "CentovaCast"),
                    ("rcast", "Rcast"),
                    ("azuracast", "AzuraCast"),
                    ("everestpanel", "EverestPanel"),
                    ("radioking", "RadioKing"),
                ],
                default="shoutcast",
                max_length=50,
            ),
        ),
    ]
