# Generated by Django 4.2.6 on 2024-03-14 15:43
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("radio", "0003_remove_radio_url_api_radio_radio_id_radioking_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="radio",
            name="url_server_radio",
            field=models.URLField(blank=True),
        ),
    ]
