# Generated by Django 4.2.6 on 2024-04-10 10:01
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("radio", "0005_radiomenumodel_radio_radio_by_user_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="radio",
            constraint=models.UniqueConstraint(
                fields=("name",), name="unique_radio_name"
            ),
        ),
    ]
