# Generated by Django 4.2.6 on 2024-04-14 21:16
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("radio", "0006_radio_unique_radio_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="radio",
            options={
                "verbose_name": "Radio",
                "verbose_name_plural": "Radios management",
            },
        ),
    ]
