# Generated by Django 4.2.6 on 2024-04-14 21:25
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("radio", "0007_alter_radio_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="radio",
            options={
                "verbose_name": "Radio",
                "verbose_name_plural": "Radio management",
            },
        ),
    ]
