# Generated by Django 4.2.6 on 2024-04-15 01:19
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("radio", "0008_alter_radio_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="radio",
            name="url_server_radio",
            field=models.URLField(blank=True, verbose_name="url de la radio"),
        ),
    ]
