# Generated by Django 4.2.6 on 2024-04-15 01:21
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("radio", "0009_alter_radio_url_server_radio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="radio",
            name="url_server_radio",
            field=models.URLField(blank=True),
        ),
    ]
