# Generated by Django 4.2.6 on 2024-04-15 22:39
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("radio", "0010_alter_radio_url_server_radio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="radiomenumodel",
            options={
                "verbose_name": "radio menu",
                "verbose_name_plural": "radio menus",
            },
        ),
        migrations.AlterField(
            model_name="radio",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="radio",
            name="id_radioking",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="id radioking"
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="is active"),
        ),
        migrations.AlterField(
            model_name="radio",
            name="name",
            field=models.CharField(max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="radio",
            name="radio_account_port",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="radio account port"
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="radio_image_icon",
            field=models.FileField(
                blank=True,
                upload_to="uploads/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpeg", "jpg"]
                    )
                ],
                verbose_name="radio image icon",
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="server_type",
            field=models.CharField(
                choices=[
                    ("shoutcast", "Shoutcast"),
                    ("icecast", "Icecast"),
                    ("everestcast", "EverestCast"),
                    ("centovacast", "CentovaCast"),
                    ("rcast", "Rcast"),
                    ("azuracast", "AzuraCast"),
                    ("everestpanel", "EverestPanel"),
                    ("radioking", "RadioKing"),
                ],
                default="shoutcast",
                max_length=50,
                verbose_name="server type",
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="sid",
            field=models.IntegerField(
                blank=True, default=1, null=True, verbose_name="sid"
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="station_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="station id"),
        ),
        migrations.AlterField(
            model_name="radio",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="updated at"),
        ),
        migrations.AlterField(
            model_name="radio",
            name="url_api_radio_current_song",
            field=models.URLField(
                blank=True, null=True, verbose_name="url api radio current song"
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="url_api_radio_history",
            field=models.URLField(
                blank=True, null=True, verbose_name="url api radio history"
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="url_cover_default",
            field=models.URLField(verbose_name="url cover default"),
        ),
        migrations.AlterField(
            model_name="radio",
            name="url_flux_radio",
            field=models.URLField(blank=True, null=True, verbose_name="url flux radio"),
        ),
        migrations.AlterField(
            model_name="radio",
            name="url_pannel_connexion",
            field=models.URLField(
                blank=True, null=True, verbose_name="url pannel connexion"
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="url_server_radio",
            field=models.URLField(blank=True, verbose_name="url server radio"),
        ),
        migrations.AlterField(
            model_name="radio",
            name="url_site",
            field=models.URLField(verbose_name="url site"),
        ),
        migrations.AlterField(
            model_name="radio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_radio",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="radio",
            name="username_radio_account",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="username radio account",
            ),
        ),
        migrations.AlterField(
            model_name="radiomenumodel",
            name="link",
            field=models.URLField(verbose_name="link"),
        ),
        migrations.AlterField(
            model_name="radiomenumodel",
            name="radio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="radio_menu",
                to="radio.radio",
                verbose_name="radio",
            ),
        ),
        migrations.AlterField(
            model_name="radiomenumodel",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
    ]
