# Generated by Django 4.2.6 on 2024-05-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("radio", "0011_alter_radiomenumodel_options_alter_radio_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="radiomenumodel",
            options={"verbose_name": "RadioMenu", "verbose_name_plural": "RadioMenus"},
        ),
        migrations.AlterField(
            model_name="radiomenumodel",
            name="link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="radiomenumodel",
            name="radio",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="radio_menu",
                to="radio.radio",
            ),
        ),
        migrations.AlterField(
            model_name="radiomenumodel",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
