# Generated by Django 4.2.6 on 2023-11-23 14:23
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ekilauth", "0002_alter_usermodel_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_by_user",
                to="ekilauth.usermodel",
            ),
        ),
    ]
