# Generated by Django 4.2.6 on 2023-11-18 21:55
import django.contrib.auth.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ekilauth", "0002_alter_usermodel_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermodel",
            options={"verbose_name": "User"},
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.CharField(
                help_text="Required. 150 characters or fewer. Lowercase a-z and uppercase A-Z letters, numbers, and @/./+/-/_ characters only.",
                max_length=150,
                null=True,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
            ),
        ),
    ]
