# Generated by Django 4.2.6 on 2023-11-30 09:40
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ekilauth", "0003_alter_usermodel_options_alter_usermodel_username"),
        ("ekilauth", "0003_usermodel_created_by"),
    ]

    operations = []
