# Generated by Django 4.2.6 on 2023-12-09 19:55
import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ekilauth", "0004_merge_20231130_0940"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_user",
                to="ekilauth.usermodel",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.CharField(
                help_text="Required. 150 characters or fewer. Lowercase a-z and uppercase A-Z letters, numbers",
                max_length=150,
                null=True,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
            ),
        ),
    ]
