# Generated by Django 4.2.6 on 2024-04-14 21:16
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ekilauth", "0005_alter_usermodel_created_by_alter_usermodel_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermodel",
            options={"verbose_name": "User", "verbose_name_plural": "Users management"},
        ),
    ]
