# Generated by Django 4.2.6 on 2024-04-14 21:27
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ekilauth", "0007_alter_usermodel_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ekilauser",
            options={"verbose_name": "User", "verbose_name_plural": "User management"},
        ),
    ]
