# Generated by Django 4.2.6 on 2024-04-14 21:28
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ekilauth", "0008_alter_ekilauser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermodel",
            options={"verbose_name": "User"},
        ),
    ]
