# Generated by Django 4.2.6 on 2024-04-15 21:40
import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("ekilauth", "0009_alter_usermodel_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="confirm_number",
            field=models.CharField(
                max_length=1000, null=True, verbose_name="confirm number"
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_by_user",
                to="ekilauth.usermodel",
                verbose_name="created by",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="email"),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="is_confirmed",
            field=models.BooleanField(default=False, verbose_name="is confirmed"),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="roles",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("revendeur", "Revendeur"),
                    ("client", "Client"),
                ],
                default="client",
                max_length=50,
                verbose_name="role",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="username",
            field=models.CharField(
                help_text="Required. 150 characters or fewer. Lowercase a-z and uppercase A-Z letters, numbers",
                max_length=150,
                null=True,
                validators=[django.contrib.auth.validators.ASCIIUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
